# https://www.joshmedeski.com/posts/setting-up-alacritty-for-a-fast-minimal-terminal-emulator/
# https://alacritty.org/config-alacritty.html
# https://alacritty.org/config-alacritty-bindings.html
# https://github.com/alacritty/alacritty-theme
import = [
#   "~/.config/alacritty/themes/themes/nord.toml",
#   "~/.config/alacritty/themes/themes/carbonfox.toml",
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml",
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[shell]
program = "tmux"

[window]
# opacity = 0.9
decorations = "NONE"
# startup_mode = "Maximized"
padding = { x = 0, y = 0 }
# dimensions = { columns = 120, lines = 36 }

[font]
size = 12.25
offset = { y = 2 }

[font.normal]
family = "FiraCode Nerd Font"
style = "Medium"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Medium Italic"

