# Ashell log level filter, possible values "DEBUG" | "INFO" | "WARNING" | "ERROR". Needs reload
logLevel: "INFO" # optional, default "INFO"
# Ashell bar position, possible values Top | Bottom. Needs reload
# position: Top # optional, default Top
# App lancher commanda, it will be used to open the launcher,
# without a value the related button will not appear
# appLauncherCmd: "~/.config/rofi/launcher.sh" # optional, default None 
# Clipboard command, it will be used to open the clipboard menu,
# without a value the related button will not appear
# clipboardCmd: "cliphist-rofi-img | wl-copy"  # optional, default None 
# Update module configuration. 
# Without a value the related button will not appear.
updates: # optional, default None 
  # The check command will be used to retrieve the update list.
  # It should return something like `package_name version_from -> version_to\n`
  checkCmd: "checkupdates; paru -Qua" # required
  # The update command is used to init the OS update process
  updateCmd: "alacritty -e bash -c \"paru; echo Done - Press enter to exit; read\" &" # required
# Maximum number of chars that can be present in the window title
# after that the title will be truncated 
truncateTitleAfterLength: 150 # optional, default 150
# The system module configuration
# system: 
#   disabled: false # Enable or disable the system monitor module
#   cpuWarnThreshold: 6O # cpu indicator warning level (default 60)
#   cpuAlertThreshold: 8O # cpu indicator alert level (default 80)
#   memWarnThreshold: 7O # mem indicator warning level (default 70)
#   memAlertThreshold: 85 # mem indicator alert level (default 85)
#   tempWarnThreshold: 6O # temperature indicator warning level (default 60)
#   tempAlertThreshold: 8O # temperature indicator alert level (default 80)
# Clock module configuration
clock:
  # clock format see: https://docs.rs/chrono/latest/chrono/format/strftime/index.html 
  format: "%a %d %b %R" # optional, default: %a %d %b %R
# Settings module configuration
settings:
  # command used for lock the system
  # without a value the related button will not appear 
  lockCmd: "hyprlock &" # optional, default None 
  # command used to open the sinks audio settings 
  # without a value the related button will not appear 
  audioSinksMoreCmd: "pavucontrol -t 3" # optional default None 
  # command used to open the sources audio settings
  # without a value the related button will not appear 
  audioSourcesMoreCmd: "pavucontrol -t 4" # optional, default None 
  # command used to open the network settings 
  # without a value the related button will not appear 
  wifiMoreCmd: "nm-connection-editor" # optional, default None
  # command used to open the VPN settings 
  # without a value the related button will not appear 
  vpnMoreCmd: "nm-connection-editor" # optional, default None 
  # command used to open the Bluetooth settings  
  # without a value the related button will not appear 
  bluetoothMoreCmd: "blueman-manager" # optional, default None 
# Appearance config 
# Each color could be a simple hex color like #228800 or an 
# object that define a base hex color and two optional variant of that color (a strong one and a weak one)
# and the text color that should be used with that base color
# example:
# backgroundColor:
#   base: #448877
#   strong: #448888 -- optional default autogenerated from base color
#   weak: #448855 -- optional default autogenarated from base color
#   text: #ffffff -- optional default base text color
# appearance:
#     backgroundColor: "#1e1e2e" # used as a base background color for header module button
#     primaryColor: "#fab387" # used as a accent color
#     secondaryColor: "#11111b" # used for darker background color 
#     successColor: "#a6e3a1" # used for success message or happy state
#     dangerColor: "#f38ba8" # used for danger message or danger state (the weak version is used for the warning state
#     textColor: "#f38ba8" # base default text color
#     # this is a list of color that will be used in the workspace module (one color for each monitor)
#     workspaceColors: 
#       - "#fab387" 
#       - "#b4befe"
#     # this is a list of color that will be used in the workspace module 
#     # for the special workspace (one color for each monitor)
#     # optional, default None
#     # without a value the workspaceColors list will be used
#     specialWorkspaceColors:
#       - "#a6e3a1" 
#       - "#f38ba8"
