"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "cyan"
truncate_to_repo = false

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vicmd_symbol = "[❮](bold purple)"

[git_branch]
format = "[$branch $symbol]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
ahead = " ⇡$count"
behind = " ⇣$count"
deleted = " -$count"
diverged = " V$count"
stashed = "≡$count"
modified = " ~$count"
staged = '[ ^ $count ](green)'
renamed = " $count"
untracked = " #$count"
conflicted = ""

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
# format = "[$duration]($style) "
format = ""
style = "yellow"

[python]
format = ""
style = "bright-black"

